### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by chrisjaure** [BarCampGreenBay/barcampgb.org#13]
The site needs to be designed. I've just been creating basic forms/pages for the back-end stuff.

**Comment by chrisjaure** [comment]
@kmcgillivray Still interested in helping out with the design?

**Comment by kmcgillivray** [comment]
@chrisjaure Potentially, depending on the timeline. Do you have a time in mind you want to have the new site up?

**Comment by kmcgillivray** [comment]
@chrisjaure Actually, never mind, yeah I definitely want to help out. I'll see if I can get the repo running locally and then submit pull requests with styling, if that works for you?

**Comment by chrisjaure** [comment]
Awesome @kmcgillivray! Let me know if you need any help getting it running.

I'd like to get the site up by September at the latest. We can always fall back to the old site if this one isn't done by then (that's what happened last year :P)

**Comment by kmcgillivray** [comment]
Great, I got it forked, cloned, and running locally so I should be all set. I'll give you a heads up when I start rolling with it. My good friend [Foster](https://github.com/fosterstilp) is going to help out too, but I'll be making any actual pull requests.

Looking forward to helping out and contributing!! :rocket:

**Comment by fosterstilp** [comment]
Hay Chris, nice to meet you! Can't wait to dig in and help out on this. 🎉

**Comment by chrisjaure** [comment]
Nice, can't wait to see what you two come up with :)

The UX can definitely be improved. At this point, it's pretty much Web 1.0. I plan on using React, but I haven't settled on purely client site or server side as well.

If you think something can work better, feel free to mock something up and I can add it or attempt it yourself if you think you're up for it.

Thanks!

**Comment by chrisjaure** [comment]
Design merged in f26d27f596844ac408e45cf21388007aa15c809e
